data:
    dataset_type: "cached_threedfront"
    encoding_type: "cached_graph_sincos_angle_sg2sc"
    augmentations: ["fixed_rotation"]
    dataset_directory: "dataset/InstructScene/threed_front_bedroom"
    annotation_file: "configs/bedroom_threed_front_splits.csv"
    path_to_invalid_scene_ids: "configs/invalid_threed_front_rooms.txt"
    path_to_invalid_bbox_jids: "configs/black_list.txt"
    path_to_floor_plan_textures: "configs/floor_plan_texture_images"
    path_to_pickled_3d_futute_models: "dataset/InstructScene/threed_future_model_bedroom.pkl"
    filter_fn: "threed_front_bedroom"
    train_stats: "dataset_stats.txt"
    room_layout_size: "64,64"
    max_length: 12
    angle_num_bins: 24  # not used for sincos angle encoding

model:
    name: "sg2sc_diffusion_objfeat_gtf"
    feature_extractor:
        name: "resnet18"
        input_channels: 1
        feature_size: 128
        freeze_bn: true
        pretrained: true

training:
    splits: ["train", "val"]
    epochs: 2000
    steps_per_epoch: 500
    batch_size: 128
    save_frequency: 10
    log_frequency: 1
    optimizer:
        name: "adamw"
        lr: 0.0001
        weight_decay: 0.02
    loss_weights:
        pos_mse: 1.
        size_mse: 1.
        angle_mse: 1.
    ema:
        use_ema: true
        max_decay: 0.9999
        min_decay: 0.
        update_after_step: 0
        use_warmup: true
        inv_gamma: 1.
        power: 0.75

validation:
    splits: ["test"]
    batch_size: 256
    frequency: 1
